### ISSUE TITLE
List of fishes

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#1]
### Value Proposition
---
As a user
I want to have list of fishes
in order to have an overview of typical aquarium fishes

### Description
---

![userstory1](https://user-images.githubusercontent.com/97026408/156549328-34077e12-be5b-4fab-8e47-fd7123607edf.png)

### Acceptance criteria
---

- [ ] The list is scrollable
- [ ] There is a list with the fish name and a few properties

### Tasks
- [ ] Setup project
- [ ] Create component (List, Cards)
  - [ ] Storybook
  - [ ] Test
- [ ] GlobalStyles
- [ ] Check accessibility
- [ ] Add to app
