### ISSUE TITLE
Add a filter to the Search

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#10]
### Value Proposition
---
**As a** user
**I want to** filter the fishes
**in order to** to make a pre-selection

### Description
---

With the preselection the user should be able to restrict the search.

![capstone userstorie6](https://user-images.githubusercontent.com/97026408/158159580-28a5acce-e6c2-4d82-90a6-8bce43a5b348.png)

### Acceptance criteria
---

- [ ] The fish should be filtered according to the difficulty of husbandry.
- [ ] The filter should be placed under the searchbar.

### Tasks
---
- [ ] Edit components/Searchbar
  - [ ] Styling
  - [ ] Storybook
  - [ ] Test
- [ ] Check accessibility
- [ ] Add to app
