### ISSUE TITLE
Add a watchlist

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#11]
## Value proposition

**As a** user
**I need** to have a wish/watchlist of fish
**to be able to** see the boomarked fish

## Description

![capstone userstories7](https://user-images.githubusercontent.com/97026408/158161554-4d4f4c37-47f1-4830-b561-f183c5eff522.png)

## Acceptance Criteria

- [ ] The bookmarked fish should be displayed on the wish/watchlist

## Tasks

- [ ] Create pages/WatchListPage
  - [ ] Styling
  - [ ] Storybook
  - [ ] Test
- [ ] Check accessibility
- [ ] Add to app
