### ISSUE TITLE
Add navigation bar

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#12]
## Value proposition

**As a** user
**I need** to navigate
**to be able to** switch between the pages

## Description

![capstone userstories nav](https://user-images.githubusercontent.com/97026408/158167230-5d1cf523-4b7b-4409-b1ae-4187ce00c2bb.png)

## Acceptance Criteria

- [ ] The navigation bar should show the database and wish/watchlist

## Tasks

- [ ] Create components/Navigation
  - [ ] Styling
  - [ ] Storybook
  - [ ] Test
- [ ] Add React Router
- [ ] Check accessibility
- [ ] Add to app
