### ISSUE TITLE
Page for my tank and create form for my own tank

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#16]
## Value proposition

**As a** user
**I need** to have form to create my own tank
**to be able to** show it off to others when needed

## Description

![capstone addtank](https://user-images.githubusercontent.com/97026408/159035077-fcb98318-0229-430d-9218-620d9dc9e08a.png)

## Acceptance Criteria

- [x] a list with all my tanks listed on my tanks page
- [x] a seperate page to create my own tank
- [x] a form is shown by clicking on the "add tank" button
- [x] input fields with a maxLength
- [x] in the form the user is able to add a photo of the tank
- [x] each input field is required

## Tasks
- [x] Create my tank page
- [x] edit navigation and route
- [x] Create components/CreateTankForm
  - [x] Styling
  - [x] Storybook
  - [x] Test
- [x] Check on mobile device
- [x] Add React Router
- [x] Check accessibility
- [x] Add to app
