### ISSUE TITLE
Edit my tank

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#17]
## Value proposition

**As a** user
**I need** to edit my tank
**to be able to**  to keep the data of my tank up-to-date

## Description

![capstone editmytank](https://user-images.githubusercontent.com/97026408/159224372-e0fc4b08-c523-47cd-94ac-23bff8aed06f.png)

## Acceptance Criteria

- [ ] add a edit button to my tank 
- [ ] after clicking the filled form of my tank should be displayed
- [ ] after submitting change the my tank page should be displayed again

## Tasks

- [ ] Edit My Tank Page/Card
  - [ ] Styling
  - [ ] Storybook
  - [ ] Test
- [ ] Check on mobile device
- [ ] Check accessibility
- [ ] Add to app
