### ISSUE TITLE
Delete My Tank

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#18]
## Value proposition

**As a** user
**I need** to delete my tank
**to be able to**  remove a old tank, when the fishes are gone

## Description

![capstone deletemytank](https://user-images.githubusercontent.com/97026408/159225358-68c1309c-41c2-46fa-b024-cd18173508b1.png)

## Acceptance Criteria

- [ ] add a delete button to my tank card
- [ ] confirmation form to be displayed
- [ ] the showcase is empty

## Tasks

- [ ] Edit my tank card
- [ ] Create a confirmation form
  - [ ] Styling
  - [ ] Storybook
  - [ ] Test
- [ ] Check on mobile device
- [ ] Check accessibility
- [ ] Add to app
