### ISSUE TITLE
Create toggle for the fish card 

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#2]
### Value Proposition
---
**As a** user
**I want to** see more details of the fish
**in order to** see if the fish fits to the own aquarium

### Description
---

When you click on the card, you should see more information about the fish, such as size and water temperature.

![userstory2-update](https://user-images.githubusercontent.com/97026408/156735316-be344fca-92fc-4d7e-849f-a93b3c99460c.png)

### Acceptance criteria
---

- [x] The card expands when you click on it and closes again when you click on it for the second time

### Tasks
---
- [x] Add a toggle for the card element
  - [x] Storybook
  - [x] Test
- [x] Check accessibility
- [x] Add to app
