### ISSUE TITLE
Adding images of fish

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#3]
### Value Proposition
---
**As a** user
**I want to** see a picture of the fish
**in order to** have an impression of the fish

### Description
---

In addition to the description of the fish, a sample image should be displayed so that the user can see whether the selected fish is visually appealing. To do this, the cards must be realigned and adapted.

![userstory3-update](https://user-images.githubusercontent.com/97026408/156737206-3e779a7a-481a-4063-9de1-c252e9c5dabe.png)

### Acceptance criteria
---

- [ ] The arrangement of images and text should not move when the card is opened

### Tasks
---
- [ ] Edit components/Card
  - [ ] Storybook
  - [ ] Test
- [ ] Check accessibility
- [ ] Add to app
