### ISSUE TITLE
Add bookmark to cards

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#4]
### Value Proposition
---
**As a** user
**I want to** bookmark fishes
**in order to** mark fish of interest for a wish/watchlist

### Description
---

The fish card should be provided with a bookmark to mark those that are interesting for the user or are already in possession.

![userstory4-update](https://user-images.githubusercontent.com/97026408/156745669-23ffdb8b-ad80-4242-84e2-ffe77e3f0eec.png)

### Acceptance criteria
---

- [ ] The bookmark should be able to be selected and deselected.
- [ ] The bookmark button should change its appearance when clicked.

### Tasks
---
- [ ] Add bookmarks to components/Card
  - [ ] Storybook
  - [ ] Test
- [ ] Check accessibility
- [ ] Add to app
