### ISSUE TITLE
Adding a searchbar

### ISSUE THREAD

**Issue by hennifant** [hennifant/capstone-project#5]
### Value Proposition
---
As a user
I want to search the list of fishes
in order to avoid having to scroll through the whole list

### Description
---

With the help of the searchbar, the user should be able to search the list of fish.

![userstory5](https://user-images.githubusercontent.com/97026408/156603012-ccce87f1-c83b-48da-9870-e5e5d108992a.png)

### Acceptance criteria
---

- [ ] The fishes are to be found by their name through the search.
- [ ] The searchbar is not scrollable and fixed to the bottom of the viewport

### Tasks
---
- [ ] Create components/Searchbar
  - [ ] Styling
  - [ ] Storybook
  - [ ] Test
- [ ] Check accessibility
- [ ] Add to app
